### ISSUE TITLE
CurseForge?

### ISSUE THREAD

**Issue by Kasualix** [GBLodb/PreventCrappyLauncher#1]
如题，有考虑上curseforge发模组吗？

**Comment by GBLodb** [comment]
没有做过 icon 如果有人愿意提供 那我会尝试上传 CurseForge/Modrinth

另外 尽管此 mod 源代码以 MPLv2 协议授权 我仍对任何人开放二次分发本 mod 相关官方信息和我在 GitHub Release 中发布的本 mod 二进制文件的授权 前提是署名且要二次分发到的站点没有被 [StopModReposts](stopmodreposts.org) 收录

**Comment by Kasualix** [comment]
![image](https://user-images.githubusercontent.com/110756250/187922754-63610777-8919-46c6-b1d1-0d262f5c2fd4.png)
搓了一个，可以吗？

**Comment by GBLodb** [comment]
[自己整了个](https://github.com/GBLodb/PreventCrappyLauncher/blob/retro/icon.png) CurseForge 和 Modrinth 都发了等审核

**Comment by GBLodb** [comment]
https://modrinth.com/mod/preventcrappylauncher
CurseForge 还是一如既往的慢

**Comment by GBLodb** [comment]
https://www.curseforge.com/minecraft/mc-mods/prevent-crappy-launcher
